server:
  port: 8071
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/ipw?useSSL=false'
    username: root
    password: sysop
  jpa.hibernate.ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
