server:
  port: 8071
spring:
  h2.console:
      enabled: true
      path: '/console'
  datasource.url: 'jdbc:h2:file:/Users/Piotr/bazaH2/baza'
  jpa.hibernate.ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: '*'
